### ISSUE TITLE
Appcrash when hover or right-click taskbar icon

### ISSUE THREAD

**Issue by danchar4** [FireCubeStudios/FluentFlyouts#14]
Config:
- Surface Laptop Studio
- Latest Win11 2022H2
- ExplorerPatcher installed
- MS PowerToys installed

Repro Steps:
- d/l from MS Store
- run app manually from start menu
- click on new battery icon in taskbar -> window pops up and displys OK
- hover or right-click on taskbar icon again ->crash

Stack trace:
0:000> k
 # ChildEBP RetAddr      
00 02d7e670 6e85b3a4     KERNELBASE!RaiseException+0x62
01 02d7e71c 6e85b246     coreclr!RaiseTheExceptionInternalOnly+0x146 [D:\a\_work\1\s\src\coreclr\vm\excep.cpp @ 2807] 
02 02d7e7b4 6c1418ac     coreclr!IL_Throw+0x86 [D:\a\_work\1\s\src\coreclr\vm\jithelpers.cpp @ 4119] 
03 02d7e7c0 17a5b0d9     WinRT_Runtime!WinRT.ExceptionHelpers.<ThrowExceptionForHR>g__Throw|20_0+0x3c
04 02d7e81c 17ae1f9a     WinRT_Runtime!WinRT.ExceptionHelpers.ThrowExceptionForHR+0x9
05 02d7e81c 6c697bbe     Microsoft_WinUI!ABI.Microsoft.UI.Xaml.Controls.IToolTipMethods.set_IsOpen+0xca
06 02d7e828 5f15512f     Microsoft_WinUI!Microsoft.UI.Xaml.Controls.ToolTip.set_IsOpen+0x1e
07 02d7e834 5f0280f2     H_NotifyIcon_WinUI!H.NotifyIcon.TaskbarIcon.OnToolTipChange+0x4f
08 02d7e85c 5f027c95     H_NotifyIcon!H.NotifyIcon.Core.MessageWindow.ProcessWindowMessage+0x3e2
09 02d7e8a8 13d56e8d     H_NotifyIcon!H.NotifyIcon.Core.MessageWindow.OnWindowMessageReceived+0x45
WARNING: Frame IP not in any known module. Following frames may be wrong.
0a 02d7e8f4 774d2553     0x13d56e8d
0b 02d7e920 774c3316     USER32!_InternalCallWinProc+0x2b
0c 02d7ea18 774c2d7a     USER32!UserCallWinProcCheckWow+0x4c6
0d 02d7ea7c 774ccccf     USER32!DispatchClientMessage+0xea
0e 02d7eab8 776d8b0d     USER32!__fnDWORD+0x3f
0f 02d7eb30 76ab10dc     ntdll!KiUserCallbackDispatcher+0x4d
10 02d7eb30 774cf710     win32u!NtUserGetMessage+0xc
11 02d7eb30 6b19b8e9     USER32!GetMessageW+0x30
12 02d7eb78 6b0df166     Microsoft_ui_xaml!DirectUI::FrameworkApplication::RunDesktopWindowMessageLoop+0x21
13 02d7ebe4 08c9d1a7     Microsoft_ui_xaml!DirectUI::FrameworkApplicationFactory::Start+0x266
14 02d7ec5c 6c5be246     Microsoft_WinUI!ABI.Microsoft.UI.Xaml.IApplicationStaticsMethods.Start+0xa7
15 02d7ec68 6d136802     Microsoft_WinUI!Microsoft.UI.Xaml.Application.Start+0x16
16 02d7eca8 6e88becf     FluentFlyouts3!FluentFlyouts3.Program.Main+0x62
17 02d7ecb4 6e7d49da     coreclr!CallDescrWorkerInternal+0x34
18 02d7ece8 6e7d5bba     coreclr!CallDescrWorkerWithHandler+0x66 [D:\a\_work\1\s\src\coreclr\vm\callhelpers.cpp @ 69] 
19 02d7ed5c 6e836a3a     coreclr!MethodDescCallSite::CallTargetWorker+0xe7 [D:\a\_work\1\s\src\coreclr\vm\callhelpers.cpp @ 551] 
1a (Inline) --------     coreclr!MethodDescCallSite::Call+0x11 [D:\a\_work\1\s\src\coreclr\vm\callhelpers.h @ 458] 
1b 02d7ee70 6e83691c     coreclr!RunMainInternal+0xe4 [D:\a\_work\1\s\src\coreclr\vm\assembly.cpp @ 1483] 
1c 02d7eee0 6e83681b     coreclr!RunMain+0x9f [D:\a\_work\1\s\src\coreclr\vm\assembly.cpp @ 1556] 
1d 02d7f144 6e83578d     coreclr!Assembly::ExecuteMainMethod+0x17c [D:\a\_work\1\s\src\coreclr\vm\assembly.cpp @ 1672] 
1e 02d7f214 6e8363c6     coreclr!CorHost2::ExecuteAssembly+0x13d [D:\a\_work\1\s\src\coreclr\vm\corhost.cpp @ 384] 
1f 02d7f268 6ebb63c4     coreclr!coreclr_execute_assembly+0xc6 [D:\a\_work\1\s\src\coreclr\dlls\mscoree\unixinterface.cpp @ 446] 
20 (Inline) --------     hostpolicy!coreclr_t::execute_assembly+0x31 [D:\a\_work\1\s\src\native\corehost\hostpolicy\coreclr.cpp @ 89] 
21 02d7f314 6ebb65c2     hostpolicy!run_app_for_context+0x414 [D:\a\_work\1\s\src\native\corehost\hostpolicy\hostpolicy.cpp @ 255] 
22 02d7f348 6ebb6d75     hostpolicy!run_app+0x52 [D:\a\_work\1\s\src\native\corehost\hostpolicy\hostpolicy.cpp @ 284] 
23 02d7f45c 6ec09ad3     hostpolicy!corehost_main+0xf5 [D:\a\_work\1\s\src\native\corehost\hostpolicy\hostpolicy.cpp @ 430] 
24 02d7f4d8 6ec0b909     hostfxr!execute_app+0x253 [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 147] 
25 02d7f560 6ec0d594     hostfxr!`anonymous namespace'::read_config_and_execute+0xb9 [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 533] 
26 02d7f5c8 6ec0bc98     hostfxr!fx_muxer_t::handle_exec_host_command+0x104 [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 1018] 
27 02d7f6c8 6ec06f1b     hostfxr!fx_muxer_t::execute+0x238 [D:\a\_work\1\s\src\native\corehost\fxr\fx_muxer.cpp @ 594] 
28 02d7f760 008eeada     hostfxr!hostfxr_main_startupinfo+0x8b [D:\a\_work\1\s\src\native\corehost\fxr\hostfxr.cpp @ 61] 
29 02d7f8a8 008eee1a     apphost!exe_start+0x79a [D:\a\_work\1\s\src\native\corehost\corehost.cpp @ 235] 
2a 02d7f8cc 008eff4c     apphost!wmain+0x8a [D:\a\_work\1\s\src\native\corehost\corehost.cpp @ 304] 
2b (Inline) --------     apphost!invoke_main+0x1c [d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 90] 
2c 02d7f914 76057ba9     apphost!__scrt_common_main_seh+0xfa [d:\a01\_work\11\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl @ 288] 
2d 02d7f924 776cbb3b     KERNEL32!BaseThreadInitThunk+0x19
2e 02d7f97c 776cbabf     ntdll!__RtlUserThreadStart+0x2b
2f 02d7f98c 00000000     ntdll!_RtlUserThreadStart+0x1b

Also see several crashes in reliability monitor with different exception codes:

Description
Faulting Application Path:	C:\Program Files\WindowsApps\2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j\FluentFlyouts3\FluentFlyouts3.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j
Application Name:	praid:App
Application Version:	1.0.0.0
Application Timestamp:	62b2f9e3
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.22621.608
Fault Module Timestamp:	507feee9
Exception Code:	e0434352
Exception Offset:	00147172
OS Version:	10.0.22621.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	cbeb
Additional Information 2:	cbebd3de5c942e8f30fbbdd310ec239d
Additional Information 3:	eef3
Additional Information 4:	eef3cc04e40f2000dc8fcbed141dbc02

Extra information about the problem
Bucket ID:	28e248384c8d86d9e308dbb1e1902232 (1371587643574329906)

Description
Faulting Application Path:	C:\Program Files\WindowsApps\2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j\FluentFlyouts3\FluentFlyouts3.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j
Application Name:	praid:App
Application Version:	1.0.0.0
Application Timestamp:	62b2f9e3
Fault Module Name:	KERNELBASE.dll
Fault Module Version:	10.0.22621.608
Fault Module Timestamp:	507feee9
Exception Code:	c000041d
Exception Offset:	00147172
OS Version:	10.0.22621.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	5389
Additional Information 2:	5389d0f7215dfad9ea476a2a89ef299d
Additional Information 3:	9f0c
Additional Information 4:	9f0c79078b813abecb3f1c693a4c9d96

Extra information about the problem
Bucket ID:	25e5721f045017f813b1b7d46cdaa09b (1419117480585633947)

Description
Faulting Application Path:	C:\Program Files\WindowsApps\2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j\FluentFlyouts3\FluentFlyouts3.exe

Problem signature
Problem Event Name:	MoAppCrash
Package Full Name:	2505FireCubeStudios.FluentFlyouts_3.0.8.0_x86__k45w5yt88e21j
Application Name:	praid:App
Application Version:	1.0.0.0
Application Timestamp:	62b2f9e3
Fault Module Name:	combase.dll
Fault Module Version:	10.0.22621.608
Fault Module Timestamp:	b1f276d8
Exception Code:	80131509
Exception Offset:	0008fba1
OS Version:	10.0.22621.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	e4b7
Additional Information 2:	e4b7ec8b5bef5cbbbd0c917ae3e77d03
Additional Information 3:	3eb0
Additional Information 4:	3eb0b65cff216cc320bcb777418440a5

Extra information about the problem
Bucket ID:	a95fc3c91794630b16d8253022bd8187 (1646106552475419015)

**Comment by danchar4** [comment]
propose duping this to #11

**Comment by danchar4** [comment]
[memory.dmp.txt](https://github.com/FireCubeStudios/FluentFlyouts3/files/9749535/memory.dmp.txt)

**Comment by danchar4** [comment]
I tried to reproduce the issue under Windows Sandbox (installing via the powershell Add-AppPackage interface to the URLs spit out by https://store.rg-adguard.net/.) App installs fine and is not crashing in sandbox.

However, once I install [ExplorerPatcher](https://github.com/valinet/ExplorerPatcher/releases) inside the sandbox and enable the Win10 style menu for Win11, it crashes again.



![image](https://user-images.githubusercontent.com/13006912/195151997-b4be185f-71e5-44be-a6dd-eb7d21d9f26a.png)

**Comment by FireCubeStudios** [comment]
please try the new 3.1.9.0 store release

**Comment by danchar4** [comment]
Still crashes in 3.1.9.0 in the same manner

**Comment by FireCubeStudios** [comment]
Ok I know the issue. Exploreroatcher is interfering with this. Unfortunately idk how to workaround for this with winui 3 limitations. Can you try testing the v2 xaml islands app to see if that crashes

**Comment by FireCubeStudios** [comment]
Here is v2 xaml islands https://github.com/FireCubeStudios/Fluent-Flyouts-Battery-Preview-Alternative

**Comment by FireCubeStudios** [comment]
Does hover still crash or is that fixed now?

**Comment by davidmarkscott** [comment]
I have the same issue with the MS Store version, but I do **not** have this issue with this forked version - https://github.com/FireCubeStudios/Fluent-Flyouts-Battery-Preview-Alternative

With the MS Store version, right clicking will crash the application.
With the forked version, right clicking shows this dialog
![image](https://user-images.githubusercontent.com/418723/197311098-39bc8e6d-a0bc-4ea1-9bff-43c82504b11b.png)

The forked version seems to work fine (except the power saving modes.... as stated in the github project of the fork)

**Comment by FireCubeStudios** [comment]
@davidmarkscott the forked version is actually the v2 xaml Islands version. It doesn't use winui 3 like the current v3. Since it doesn't crash on right click seems to be do to xaml islands

**Comment by FireCubeStudios** [comment]
![image](https://github.com/user-attachments/assets/1079b545-aa25-4f6e-bfe3-a3b2eb11906e)
fixed
