### ISSUE TITLE
Option for white taskbar icon

### ISSUE THREAD

**Issue by Mladia** [FireCubeStudios/FluentFlyouts#18]
The taskbar image can be hard to read if it has only a black color.
A better solution would be to have the possibility choose between a white and a dark color for the battery icon in the taskbar.

![image](https://user-images.githubusercontent.com/15912404/195039353-5bfc4c39-b5ef-47a8-aa00-ab0068677c48.png)

**Comment by FireCubeStudios** [comment]
White icon already exists and is used for dark mode. Try restarting the app to see what happens

**Comment by Mladia** [comment]
I can confirm that when using dark mode, the battery icon turns white.
In my case, I am actually using light mode, but I have turned the taskbar black. As a consequence, the battery indicator is black (as it should be in light mode) and is hard to recognize on the dark taskbar.

**Comment by FireCubeStudios** [comment]
How did you turn the taskbar black?

**Comment by FireCubeStudios** [comment]
Ok so I looked into this and I don't see any way to get the windows theme for windows. I can only use the app theme

**Comment by Mladia** [comment]
A possible solution would be to have an option in the settings to always use either Black or White Icons for the Battery indicator. This makes the menu more convoluted, but is probably the only solution.

**Comment by FireCubeStudios** [comment]
Found a fix for v4 using Community toolkit
