### ISSUE TITLE
Completly Off Screen Flyout

### ISSUE THREAD

**Issue by brunobola** [FireCubeStudios/FluentFlyouts#31]
When using several desktop screens with diferent resolutions and ppi, the flyouts can bê off screen.

To make a workaround I believe that an option to make visible in center of the primary screen would bê great, it only moves the flyout to the screen, the current features could be maintained.

Thanks for the work.

**Comment by FireCubeStudios** [comment]
![image](https://github.com/user-attachments/assets/9032e8b6-b8c2-4d3c-b3f1-cd1556bc7c51)
fixed
