### ISSUE TITLE
Tray icon disappears when interacted with (hover or right-click)

### ISSUE THREAD

**Issue by D-Maxwell** [FireCubeStudios/FluentFlyouts#32]
Hello there,

I was looking for a decent battery tray widget as the default one windows 10 provides is objectively garbage. (sorry not sorry)
Your app seems like a much better option, thus I wanted to try it out as a replacement.
I love the design you've gone for, and having downloaded an older fork of yours as I was roaming around the issues others had, I realised just how much progress you had made.

Except there is one glaring issue I have encountered : *app no worky*

So basically whenever I open the app, it creates a widget in the taskbar, which works just fine... for a dozen seconds, before vanishing. No visible error message, no flashing, no explorer crashing, just straight up disappears.
Which is quite bothersome, as I would like for it to stay in place of the default widget permanently.

I may provide you with the information of the possibly linked system modifications I have done so far:
- installed TranslucentTB ;
- reverted the battery flyout to its windows 7 look using WinAero Tweaker ;
- installed many redundant libraries as I was trying to install the app outside of the Microsoft Store.

**Comment by D-Maxwell** [comment]
After some more tinkering I have found the crash occurs upon hovering or right clicking the tray icon. If I avoid these actions the application behaves as expected.

> Thus this issue is probably a duplicate of #14 or #11.

At first I thought I had the same issue with the forked version, as it seemed to crash randomly as well; I simply hadn't realised clicking the cross button within the context menu was supposed to close the app entirely rather than simply closing the context menu itself. So in the end, the fork is behaving as expected, even when hovered or right clicked (even though there is no tooltip on hover as reported in #11).

I should perhaps also point out the fact that I am using the Files app instead of the default explorer app, and have made a few registry tweaks to get it in place of explorer.exe for most calls, but since Window's Desktop Environment is merged with their explorer, it is still active.
_____
I wish to know if this project is still under development, and if these issues are considered and acknowledged, as they are, on the surface at least, the main and only issues preventing this app from being usable daily.
_____
Is this caused by some missing libraries perhaps? I ended up installing it from the Microsoft Store (I originally planned not to as I despise Microsoft, their monopoly and their bloat, and also because it refused to download any packages because of a random policy that prevented it from doing so), but for now I will be using the [temporary fork](https://github.com/FireCubeStudios/Fluent-Flyouts-Battery-Preview-Alternative) you have provided in #14.

It really is quite a shame these issues are still present to this day, though I suppose there must be understandable reasons for their correction not to have been made/published. Or perhaps they have already been and I've done something wrong ?

**Comment by D-Maxwell** [comment]
(perhaps right clicking does not crash the app but since in order to right click you must hover the icon then maybe the issue only comes from the hovering, and thus probably the tooltip libraries? Im on windows 10)

**Comment by CaioOliveiraw** [comment]
Hey @D-Maxwell did you solved this? thx!

**Comment by FireCubeStudios** [comment]
@D-Maxwell @CaioOliveiraw A fix is coming in v4. I found the issue already and as can be seen in my other apps (Clippy, Run) the new tray system works fine so yeah this fix will come

**Comment by D-Maxwell** [comment]
> @D-Maxwell @CaioOliveiraw A fix is coming in v4. I found the issue already and as can be seen in my other apps (Clippy, Run) the new tray system works fine so yeah this fix will come

Any news regarding the release of v4 ?

**Comment by cosmicice0** [comment]
any updates?

**Comment by leonlight02** [comment]
Are there anyone Who fixed the problem, because it's still there

**Comment by stamminator** [comment]
It's a shame that what looks like an otherwise polished and useful app has been left in a totally inoperable state for two years. Having many ambitious projects going on simultaneously is impressive, but critical bug fixes out to come first, especially if the fix has been known for well over a year and just needs to be patched in and released.

**Comment by FireCubeStudios** [comment]
@stamminator @leonlight02 @D-Maxwell @CaioOliveiraw 
Hello everyone sorry for years later update. I have fixed it and am working on this project again. More announcements coming soon

![image](https://github.com/user-attachments/assets/f2cda7b7-ac27-4e33-83cf-009740e3e5bc)
