### ISSUE TITLE
Tooltip is not fluent

### ISSUE THREAD

**Issue by FireCubeStudios** [FireCubeStudios/FluentFlyouts#5]
Currently tooltip uses the library implementation which is not fluent. Ideal tooltip should look like below 
![image](https://user-images.githubusercontent.com/40955345/194862937-b4c2045d-3e39-4394-bf43-d03c83ce3945.png)

**Comment by Hepi34** [comment]
In the Windows 22H2 Beta, Build 22623.875 ni_release, the tooltip seems to appear fluent. Maybe it was fluent before but I didnt notice it

![image](https://user-images.githubusercontent.com/105777839/199684909-ee28611f-c78c-437f-b851-5bf75cc68745.png)

**Comment by FireCubeStudios** [comment]
Yeah new Windows fixed it
